package com.command.mutton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BakeChickenWingCommand.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//




public class BakeChickenWingCommand extends Command {
	public BakeChickenWingCommand(Barbecuer receiver) {
        super(receiver);
    }

    public void excuteCommand() {
	    receiver.bakeChickenWing();
	}
}
