package com.command.mutton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Barbecuer.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class Barbecuer {
    
    /**
     * 烤羊肉串
     */
    public void bakeMutton() {
        System.out.println("烤羊肉串");
    }
    
    public void bakeChickenWing(){
        System.out.println("烤鸡翅");
    }
}
