package org.omg.IOP;


/**
* org/omg/IOP/CodecFactoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u77/6540/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Sunday, March 20, 2016 10:01:25 PM PDT
*/


/**
   * <code>Codecs</code> are obtained from the <code>CodecFactory</code>. 
   * The <code>CodecFactory</code> is obtained through a call to 
   * <code>ORB.resolve_initial_references( "CodecFactory" )</code>.
   */
abstract public class CodecFactoryHelper
{
  private static String  _id = "IDL:omg.org/IOP/CodecFactory:1.0";

  public static void insert (org.omg.CORBA.Any a, CodecFactory that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CodecFactory extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CodecFactoryHelper.id (), "CodecFactory");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CodecFactory read (org.omg.CORBA.portable.InputStream istream)
  {
      throw new org.omg.CORBA.MARSHAL ();
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CodecFactory value)
  {
      throw new org.omg.CORBA.MARSHAL ();
  }

  public static CodecFactory narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CodecFactory)
      return (CodecFactory)obj;
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  public static CodecFactory unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CodecFactory)
      return (CodecFactory)obj;
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

}
