package com.Composite;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Composite.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public class Composite extends Component {
    private List<Component> components = new ArrayList<>();

    public Composite(String name) {
        super(name);
    }

    public void add(Component component) {
        components.add(component);
    }

    public void remove(Component component) {
        components.remove(component);
    }

    public void display(int depth) {
        System.out.println(new String("-" + depth) + " " + name);
        for (Component component : components) {
            component.display(depth + 2);
        }
    }
}
