package com.Composite.company;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteCompany.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public class ConcreteCompany extends Company {
    private List<Company> companys=new ArrayList<>();
    public ConcreteCompany(String name) {
        super(name);
    }

    public void add(Company company) {
        companys.add(company);
    }

    public void remove(Company company) {
        companys.remove(company);
    }

    public void show(int depth) {
        System.out.println(new String("-" + depth) + " " + name);
        for (Company company : companys) {
            company.show(depth+1);
        }
    }

    public void lineofDuty() {
        for (Company company : companys) {
            company.lineofDuty();
        }
    }
}
