package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Locator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u77/6540/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Sunday, March 20, 2016 10:01:24 PM PDT
*/

public interface Locator extends LocatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Locator
