package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/ServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u77/6540/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Sunday, March 20, 2016 10:01:24 PM PDT
*/

public interface ServerManagerOperations  extends com.sun.corba.se.spi.activation.ActivatorOperations, com.sun.corba.se.spi.activation.LocatorOperations
{
} // interface ServerManagerOperations
