package com.memento.game;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RoleState.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public class RoleState {
    public int vik;
    public int atk;
    public int def;

    public RoleState(int vik, int atk, int def) {
        super();
        this.vik = vik;
        this.atk = atk;
        this.def = def;
    }

}
