package com.singleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Singleton.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//




public class Singleton {
	private static Singleton instance;
	private Singleton(){
	    
	}
	public synchronized static Singleton getInstance() {
	    if (instance==null) {
             instance=new Singleton();
        }
	    return instance;
	}
}
