package com.memento;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Memento.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public class Memento {
    public String state;

    public Memento(String state) {
        this.state=state;
    }
}
