package com.memento;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Caretaker.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public class Caretaker {
    public Memento memento;

    public Memento getMemento() {
        return memento;
    }

    public void setMemento(Memento memento) {
        this.memento = memento;
    }
    
}
