package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u77/6540/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Sunday, March 20, 2016 10:01:25 PM PDT
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
  	 * The value representing ID_UNIQUENESS_POLICY_ID.
  	 */
  public static final int value = (int)(18L);
}
