package com.visitor.visitor;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteElementA.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//




public class ConcreteElementA extends Element {
	public void accept(Visitor visitor) {
	    visitor.visitorConcreteElementA(this);
	}
}
