package com.visitor.visitor;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteElementB.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class ConcreteElementB extends Element {
    public void accept(Visitor visitor) {
        visitor.visitorConcreteElementB(this);
    }
}
