package com.visitor.visitor;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Element.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public abstract class Element {
    public abstract void accept(Visitor visitor);
}
