package com.visitor.visitor;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Visitor.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public abstract class Visitor {
    public abstract void visitorConcreteElementA(ConcreteElementA concreteElementA);

    public abstract void visitorConcreteElementB(ConcreteElementB concreteElementB);
}
