package com.flyweight;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 2016/9/28
//  @ Author : 
//
//

public class Client {
    public static void main(String[] args) {
        int extrinsicstate = 22; //代码外部状态
        FlyweightFactory flyweightFactory = new FlyweightFactory();
        Flyweight fx = flyweightFactory.getFlyweight("x");
        fx.operation(--extrinsicstate);
        
        Flyweight fy=flyweightFactory.getFlyweight("y");
        fy.operation(--extrinsicstate);
        
        Flyweight fz=flyweightFactory.getFlyweight("z");
        fz.operation(--extrinsicstate);
        
        Flyweight uf=new UnsharedConcreteFlyweight();
        uf.operation(--extrinsicstate);
    }

}
