package com.flyweight;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnsharedConcreteFlyweight.java
//  @ Date : 2016/9/28
//  @ Author : 
//
//




public class UnsharedConcreteFlyweight extends Flyweight {
    @Override
	public void operation(int extrinsicstate) {
	    System.out.println("不共享具体Flyweight"+extrinsicstate);
	}
}
