package com.mediator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Colleague.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public abstract class Colleague {
    protected Mediator mediator;

    public Colleague(Mediator mediator) {
        this.mediator = mediator;
    }

    public abstract void notify(String message);

    public abstract void send(String message);
}
