package com.mediator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteMediator.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class ConcreteMediator extends Mediator {
    public ConcreteColleague1 concreteColleague1;
    public ConcreteConlleage2 concreteConlleage2;

    public void setConcreteColleague1(ConcreteColleague1 concreteColleague1) {
        this.concreteColleague1 = concreteColleague1;
    }

    public void setConcreteConlleage2(ConcreteConlleage2 concreteConlleage2) {
        this.concreteConlleage2 = concreteConlleage2;
    }

    public void send(String message, Colleague colleague) {
        if (colleague.getClass().getName().equals(concreteColleague1.getClass().getName())) {
            concreteConlleage2.notify(message);
        } else {
            concreteColleague1.notify(message);
        }
    }
}
