package com.mediator;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mediator.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//




public abstract class Mediator {
	public abstract void send(String message, Colleague colleague);
}
