package com.Interpreter;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractExpression.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public abstract class AbstractExpression {
    /**
     * @param context
     */
    public abstract void interpret(Context context);
}
