package com.Interpreter;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class Client {
    public static void main(String[] args){
        Context context=new Context();
        List<AbstractExpression>  list=new ArrayList<>();
        list.add(new NonterminalExpression());
        list.add(new TerminalExpression());
        list.add(new NonterminalExpression());
        list.add(new TerminalExpression());
        
        for (AbstractExpression abstractExpression : list) {
            abstractExpression.interpret(context);
        }
    }
}
