package com.Interpreter;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NonterminalExpression.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class NonterminalExpression extends AbstractExpression {
    public void interpret(Context context) {
        System.out.println("非终端解释器");
    }
}
