package com.Interpreter;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TerminalExpression.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class TerminalExpression extends AbstractExpression {
    public void interpret(Context context) {
        System.out.println("终端解释器");
    }
}
