package com.visitor.manAndWoman;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Man.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class Man extends Human {
    public void accept(Status status) {
        status.getManResponse(this);
    }
}
