package com.visitor.manAndWoman;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Status.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//




public abstract class Status {
	public abstract void getManResponse( Man man);
	public abstract void getWomanResponse( Woman woman);
}
