package com.visitor.manAndWoman;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Woman.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//




public class Woman extends Human {
	public void accept(Status status) {
	    status.getWomanResponse(this);
	}
}
