package com.memento.game;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : gameRole.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public class GameRole {
    public int vik; //生命力
    public int atk;
    public int def;

    public void display() {
        System.out.println("当前的游戏进度是：" + vik + ";" + atk + ";" + def);
    }

    public RoleState setRoleState() {
        return new RoleState(vik, atk, def);
    }

    public void restart(RoleState roleState) {
        this.vik = roleState.vik;
        this.atk = roleState.atk;
        this.def = roleState.def;
    }
    public void setInitState(){
        this.vik=100;
        this.atk=100;
        this.def=100;
    }
    public void figth(){
        this.vik=10;
        this.atk=10;
        this.def=10;
    }
}
