package com.memento.game;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RoleStateManager.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public class RoleStateManager {
    public RoleState roleState;

    public RoleState getRoleState() {
        return roleState;
    }

    public void setRoleState(RoleState roleState) {
        this.roleState = roleState;
    }

}
