package com.command;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteCommandIpml.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class ConcreteCommand extends Command {

    public ConcreteCommand(Receiver receiver) {
       super(receiver);
    }

    public void excute() {
        super.receiver.action();
    };
}
