package com.command;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Invoker.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class Invoker {
    private Command command;

    public void setCommand(Command command) {
        this.command = command;
    }

    public void executeCommand() {
        command.excute();
    }
}
