package com.command;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Receiver.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class Receiver {
    public void action() {
        System.out.println("执行请求");
    }
}
