package com.flyweight;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteFlyweight.java
//  @ Date : 2016/9/28
//  @ Author : 
//
//

public class ConcreteFlyweight extends Flyweight {
    @Override
    public void operation(int extrinsicstate) {
        System.out.println("共享具体Flyweight" + extrinsicstate);
    }
}
