package com.flyweight;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Flyweight.java
//  @ Date : 2016/9/28
//  @ Author : 
//
//




public abstract class Flyweight {
	public abstract void operation(int extrinsicstate);
}
