package org.omg.CosNaming.NamingContextPackage;


/**
* org/omg/CosNaming/NamingContextPackage/NotFoundReason.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u77/6540/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Sunday, March 20, 2016 10:01:24 PM PDT
*/


/**
         * Indicates the reason for not able to resolve.
         */
public class NotFoundReason implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static NotFoundReason[] __array = new NotFoundReason [__size];

  public static final int _missing_node = 0;
  public static final NotFoundReason missing_node = new NotFoundReason(_missing_node);
  public static final int _not_context = 1;
  public static final NotFoundReason not_context = new NotFoundReason(_not_context);
  public static final int _not_object = 2;
  public static final NotFoundReason not_object = new NotFoundReason(_not_object);

  public int value ()
  {
    return __value;
  }

  public static NotFoundReason from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected NotFoundReason (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class NotFoundReason
