package com.flyweight.website;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WebSite.java
//  @ Date : 2016/9/28
//  @ Author : 
//
//

public abstract class WebSite {
    public abstract void use(User user);
}
