package com.ChainOfResponsibilty;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class Client {
   public static void main(String[] args){
       ConcreteHandle1 concreteHandle1=new ConcreteHandle1();
       ConcreteHandle2 concreteHandle2=new ConcreteHandle2();
       ConcreteHandle3 concreteHandle3=new ConcreteHandle3();
       
       concreteHandle1.setSuccessor(concreteHandle2);
       concreteHandle2.setSuccessor(concreteHandle3);
       
       int[] requese=new int[]{1,4,5,15,20,35,24};
       for (int i : requese) {
        concreteHandle1.handleRequest(i);
    }
       
   }
    
}
