package com.Composite.company;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.java
//  @ Date : 2016/9/30
//  @ Author : 
//
//

public abstract class Company {
    protected String name;

    public Company(String name) {
        this.name = name;
    }

    public abstract void add(Company company);

    public abstract void remove(Company company);

    public abstract void show(int depth);

    public abstract void lineofDuty();
}
