package com.mediator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class Client {
    public static void main(String[] args) {
        ConcreteMediator mediator = new ConcreteMediator();
        ConcreteColleague1 colleague1 = new ConcreteColleague1(mediator);
        ConcreteConlleage2 colleague2 = new ConcreteConlleage2(mediator);

        mediator.setConcreteColleague1(colleague1);
        mediator.setConcreteConlleage2(colleague2);
        colleague1.send("你吃饭了么？");
        colleague2.send("没有呢!你打算请客？");
    }
}
