package com.mediator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteConlleage2.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class ConcreteConlleage2 extends Colleague {
    public ConcreteConlleage2(Mediator mediator) {
        super(mediator);
    }

    public void notify(String message) {
        System.out.println("同事2接收到消息"+message);
    }

    public void send(String message) {
        mediator.send(message, this);
    }
}
