package com.Bridge;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Abstraction.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//




public abstract class Abstraction {
    protected Implementor implementor;
    public Abstraction(Implementor implementor){
        this.implementor=implementor;
    }
	public abstract void operation();
}
