package com.Bridge;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteImplementsB.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class ConcreteImplementsB extends Implementor {
    public void operationImp() {
        System.out.println("具体实现B的方法执行");
    }
}
