package com.Bridge;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteImplementsA.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//




public class ConcreteImplementsA extends Implementor {
	public void operationImp() {
	    System.out.println("具体实现A的方法执行");
	}
}
