package com.Bridge;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Implementor.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//




public abstract class Implementor {
	public abstract void operationImp();
}
