package com.flyweight.website;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteWebSite.java
//  @ Date : 2016/9/28
//  @ Author : 
//
//

public class ConcreteWebSite extends WebSite {
    private String name="";
    
    public ConcreteWebSite(String name) {
        super();
        this.name = name;
    }

    public void use(User user) {
        System.out.println("网站分类"+name+"用户："+user.getName());
    }
}
