package com.flyweight.website;

import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WebSiteFactory.java
//  @ Date : 2016/9/28
//  @ Author : 
//
//

public class WebSiteFactory {
    public Hashtable<String, Object> webSites = new Hashtable<>();

    public WebSite getWebSite(String key) {
        if (!webSites.containsKey(key)) {
            webSites.put(key, new ConcreteWebSite(key));
        }
        return (WebSite) webSites.get(key);
    }

    public int getWebSiteCount() {
        return webSites.size();
    }
}
