package com.visitor.visitor;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteVisitor2.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class ConcreteVisitor2 extends Visitor {
    public void visitorConcreteElementA(ConcreteElementA concreteElementA) {
        System.out.println(concreteElementA.getClass().getName() + "被" + this.getClass().getName()
                + "访问");

    }

    public void visitorConcreteElementB(ConcreteElementB concreteElementB) {
        System.out.println(concreteElementB.getClass().getName() + "被" + this.getClass().getName()
                + "访问");
    }
}
