package com.visitor.manAndWoman;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//

public class Client {
    public static void main(String[] args){
        ObjectStructure objectStructure=new ObjectStructure();
        objectStructure.accach(new Man());
        objectStructure.accach(new Woman());
        
        Success success=new Success();
        Failure failure=new Failure();
        objectStructure.accept(success);
        objectStructure.accept(failure);
    }
}
