package com.visitor.manAndWoman;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Human.java
//  @ Date : 2016/9/27
//  @ Author : 
//
//




public abstract class Human {
	public abstract void accept(Status status);
}
