package com.Bridge;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RefinedAbstraction.java
//  @ Date : 2016/9/29
//  @ Author : 
//
//

public class RefinedAbstraction extends Abstraction {

    public RefinedAbstraction(Implementor implementor) {
        super(implementor);
    }

    public void operation() {
        implementor.operationImp();
    }
}
